env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: latest
  sourceType: modtesule
plugins:
  - '@typescript-eslint'
  - prefer-arrow
rules:
  no-unused-vars: 1
  no-console: 0
  no-param-reassign: 0
  # 'import/prefer-default-export': 0
  # '@typescript-eslint/no-unused-vars': 0
  # '@typescript-eslint/no-explicit-any': 0
  'prefer-arrow/prefer-arrow-functions': [2, { disallowPrototype: true, singleReturnOnly: false, classPropertiesAllowed: false }]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  'react/react-in-jsx-scope': 0
  # 'jsx-a11y/no-static-element-interactions': 1
  # 'react/require-default-props': 0
  # 'jsx-a11y/label-has-associated-control': 1
  # 'react/jsx-props-no-spreading': 0